
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class AddAdvertise extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddProg
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    public AddAdvertise() {
        initComponents();
        ShowFillData();
        aname.setVisible(false);
        atime.setVisible(false);
        ProName.setVisible(false);
        aPriority.setVisible(false);
        aValid.setVisible(false);
        aname1.setVisible(false);
        atime1.setVisible(false);
        ProName1.setVisible(false);
        aPriority1.setVisible(false);
        aValid1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aname1 = new javax.swing.JLabel();
        aname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        atype = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ProName1 = new javax.swing.JLabel();
        ProName = new javax.swing.JComboBox<>();
        aPriority1 = new javax.swing.JLabel();
        atime1 = new javax.swing.JLabel();
        atime = new javax.swing.JTextField();
        aPriority = new javax.swing.JTextField();
        aValid1 = new javax.swing.JLabel();
        aValid = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        aname1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        aname1.setText("Advertise Name");

        jLabel2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel2.setText("Type");

        atype.setFont(new java.awt.Font("Snap ITC", 3, 18)); // NOI18N
        atype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Channel", "Show" }));
        atype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atypeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Snap ITC", 3, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ProName1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        ProName1.setText("Select Program");

        ProName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProNameActionPerformed(evt);
            }
        });

        aPriority1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        aPriority1.setText("Priority");

        atime1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        atime1.setText("Duration");

        aValid1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        aValid1.setText("Valid Year");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(aValid1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(aPriority1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(atime1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atime, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProName, javax.swing.GroupLayout.Alignment.TRAILING, 0, 243, Short.MAX_VALUE)
                            .addComponent(aPriority, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aValid))
                        .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atype, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(aname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atime1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProName1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aPriority1)
                    .addComponent(aPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aValid1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       System.out.print("helll");
        System.out.print(atype.getSelectedItem());
            if(!atype.getSelectedItem().toString().equals("Show")){
        try{
              Class.forName("com.mysql.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/tvchannel";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();    
           
            String Name = aname.getText();
            int Duration = Integer.parseInt(atime.getText());
            int Valid = Integer.parseInt(aValid.getText());
             System.out.println(Name+" "+Duration+""+Valid);
           
           String insertQuery = "INSERT INTO channel_ad (name,valid_year, duration) VALUES('"+Name+"','"+Valid+"','"+Duration+"')";
            stat.executeUpdate(insertQuery);
            JOptionPane.showMessageDialog(null,"Inserted successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }                                        
        else{
            try{
           Class.forName("com.mysql.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/tvchannel";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();
            String Name = aname.getText();
            String PName =(String)ProName.getSelectedItem();
            int Duration = Integer.parseInt(atime.getText());
            int Priority = Integer.parseInt(aPriority.getText());
            System.out.println(Name+"fkdfhdiuhi");
            String insertQuery = "INSERT INTO program_ad (name,program_name, duration, priority) VALUES('"+Name+"','"+PName+"','"+Duration+"','"+Priority+"')";
            
            stat.executeUpdate(insertQuery);
            JOptionPane.showMessageDialog(null,"Inserted successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }
        
        /* String type = (String)cbtype.getSelectedItem();
        String Name = tfname.getText();
        if(Name.equals("")){
            JOptionPane.showMessageDialog(this, "All feild are Required!!!!");
        }
        else if(type.equals("Channel Sponser")){
                   
            try {
                 ResultSet rs = DBLoader.executeQuery("select * from Channel_Spon");
                 
                
                rs.moveToInsertRow();
                 rs.updateString("Name", Name);
                // rs.updateString("Category", type);
                rs.insertRow();
            } catch (SQLException ex) {
                Logger.getLogger(AddAdvertise.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else
            if(type.equals("Show Sponser")){
               
            try {
                ResultSet rs = DBLoader.executeQuery("select * from ShowSpon");
                rs.moveToInsertRow();
                rs.updateString("Name", Name);
                rs.insertRow();
               
            } catch (SQLException ex) {
                Logger.getLogger(AddAdvertise.class.getName()).log(Level.SEVERE, null, ex);
            }
{
                
            }
               
        }else{
                System.out.println(type);
            }
*/
    }//GEN-LAST:event_jButton1ActionPerformed

    public void ShowFillData()
    {
        try{
            ResultSet rs=DBLoader.executeQuery("select * from program");
            while(rs.next())
            {
                ProName.addItem(rs.getString("program_name"));
                
            }
                    
        
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    
    
    private void ProNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProNameActionPerformed

    private void atypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atypeActionPerformed
        // TODO add your handling code here:
        String AddType =(String) atype.getSelectedItem();
        if(AddType.toString().equals("Channel"))
        {
        aname.setVisible(true);
        aname1.setVisible(true);
        atime.setVisible(true);
        atime1.setVisible(true);
        ProName.setVisible(false);
        ProName1.setVisible(false);
        aPriority.setVisible(false);
        aPriority1.setVisible(false);
        aValid.setVisible(true);
        aValid1.setVisible(true);
        }
        else
        {
        aname.setVisible(true);
         aname1.setVisible(true);
        atime.setVisible(true);
        atime1.setVisible(true);
        ProName.setVisible(true);
        ProName1.setVisible(true);
        aPriority.setVisible(true);
        aPriority1.setVisible(true);
        aValid.setVisible(false);
        aValid1.setVisible(false);
        
        }
    }//GEN-LAST:event_atypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ProName;
    private javax.swing.JLabel ProName1;
    private javax.swing.JTextField aPriority;
    private javax.swing.JLabel aPriority1;
    private javax.swing.JTextField aValid;
    private javax.swing.JLabel aValid1;
    private javax.swing.JTextField aname;
    private javax.swing.JLabel aname1;
    private javax.swing.JTextField atime;
    private javax.swing.JLabel atime1;
    private javax.swing.JComboBox<String> atype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
