
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laxmi
 */
public class Show extends javax.swing.JInternalFrame {

    /**
     * Creates new form Show
     */
    public Show() {
        initComponents();
        schedule sch = new schedule(textArea);
        sch.setProgram();
        getProgram();
    }

    
     void getProgram() {
			try {
                            Class.forName("com.mysql.jdbc.Driver");
                             String databaseURL = "jdbc:mysql://localhost:3306/busm";
                             Connection con = DriverManager.getConnection(databaseURL, "root", "");
                             Statement stat = con.createStatement();    
                             String selectQuery = "SELECT id,program_name,start_time,duration,category FROM program";
                             System.out.println(selectQuery);
                             ResultSet rs=stat.executeQuery(selectQuery);
                             java.sql.ResultSetMetaData rsm=rs.getMetaData();
                            
                            
                            
                                //conn = databaseConnection.connection();
				//Statement stmt = conn.createStatement();
				//ResultSet rs = stmt.executeQuery("SELECT id,program_name,start_time,duration,category FROM program ");
				if(rs.next()==false) {
					System.out.println("No such program present in database.");
					}
				else
				{
					 do{
                                             
						textArea.setText(textArea.getText()+"\n"+String.format("%-5d|%-31s|%-17s|%-9d|%-20s",rs.getInt(1),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getString(5)));
						}while(rs.next());
					
				}
			}catch(Exception e) {
				System.out.println(e.toString());
			}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
